version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mtbench
    image: mtbench:latest
    container_name: mtbench
    restart: "no"
    volumes:
      - type: bind
        source: ..
        target: /app
      - type: bind
        source: /raid/models
        target: /app/models
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["4", "5", "6", "7"]
              capabilities: [gpu]
